version: '3'

vars:
  RUN_CLI: 'frankenphp php-cli'
  RUN_WEBSERVER: 'frankenphp php-server'

tasks:
  setup-ini:
    desc: 'Generate php.ini from current FrankenPHP'
    cmds:
      - '{{.RUN_CLI}} scripts/generate-ini.php php.ini'
  setup-composer:
    desc: 'Fetch composer'
    cmds:
      - |
        {{.RUN_CLI}} -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        {{.RUN_CLI}} -r "if (hash_file('sha384', 'composer-setup.php') === 'c8b085408188070d5f52bcfe4ecfbee5f727afa458b2573b8eaaf77b3419b0bf2768dc67c86944da1544f06fa544fd47') { echo 'Installer verified'.PHP_EOL; } else { echo 'Installer corrupt'.PHP_EOL; unlink('composer-setup.php'); exit(1); }"
        {{.RUN_CLI}} composer-setup.php
        {{.RUN_CLI}} -r "unlink('composer-setup.php');"
  setup:
    desc: 'Set up all assets for workspace'
    cmds:
      - task: setup-ini
      - task: setup-composer
  composer:
    desc: 'Run composer'
    cmds:
      - '{{.RUN_CLI}} composer.phar {{.CLI_ARGS}}'
  server:
    desc: 'Start web server'
    cmds:
      - '{{.RUN_WEBSERVER}} -r public {{.CLI_ARGS}}'
