version: '3'

vars:
  FRANKENPHP_WORKDIR: '.frankenphp'
  RUN_CLI: 'frankenphp php-cli'
  RUN_WEBSERVER: 'frankenphp php-server'

dotenv:
  - '{{.FRANKENPHP_WORKDIR}}/.env'

tasks:
  setup:
    desc: 'Generate php.ini from current FrankenPHP'
    cmds:
      - '{{.RUN_CLI}} frankenphp-local/configure.php {{.FRANKENPHP_WORKDIR}} frankenphp-local/settings.php'
  cli:
    desc: 'Run CLI'
    cmds:
      - '{{.RUN_CLI}} {{.CLI_ARGS}}'
  server:
    desc: 'Start web server'
    cmds:
      - '{{.RUN_WEBSERVER}} -r public {{.CLI_ARGS}}'
  composer:
    desc: 'Run composer'
    cmds:
      - '{{.RUN_CLI}} {{.FRANKENPHP_WORKDIR}}/composer.phar {{.CLI_ARGS}}'
  php:
    desc: 'Run PHP directly'
    cmds:
      - 'php {{.CLI_ARGS}}'
